# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-19 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ftc_back', '0004_clues'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attempts', models.IntegerField()),
                ('Question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ftc_back.Question')),
                ('Teams', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ftc_back.Teams')),
            ],
        ),
    ]
