# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-19 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftc_back', '0005_tries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tries',
            name='Attempts',
            field=models.IntegerField(blank=True),
        ),
    ]
