# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-19 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftc_back', '0007_remove_tries_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='clues',
            name='clue_alphabet',
            field=models.CharField(default='a', max_length=1),
            preserve_default=False,
        ),
    ]
