# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-20 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftc_back', '0008_clues_clue_alphabet'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='name',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
