# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-21 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ftc_back', '0009_teams_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='ans',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='ques',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='id_ques',
            new_name='questionid',
        ),
    ]
